version: '3.8'

services:

  db:
    image: postgres:16
    container_name: postgres_liquibase
    environment:
      POSTGRES_DB: liquibase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: jose1234.
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase_runner
    depends_on:
      - db
    volumes:
      - ./liquibase:/liquibase/changelog
    working_dir: /liquibase/changelog
    entrypoint: ["sh", "-c"]
    command: >
      "sleep 10 &&
       liquibase --defaultsFile=liquibase.properties update"

volumes:
  pgdata: